### ISSUE TITLE
Questions about API and Provider templates

### ISSUE THREAD

**Issue by dleangen** [aQute-os/biz.aQute.osgi.util#1]
Hi!

I wanted to ask a few questions about the templates, as they are (according to my understanding) different from the templates used in the past.

Here are the differences:

 * output is now in "target" instead of "generated"
 * source files are now in src/main/java instead of src
 * test files are now in src/main/test instead of test
 * there is a new src/main/resources folder

I am interested in knowing why each these changes was made.

Thank you!

**Comment by pkriens** [comment]
I follow the maven disk layout pattern. This is quite flexible and it is easier for people to realize. It has more or less become a defacto-standard.

This is btw defined in the cnf/ext/maven-layout.bnd, not in the templates

**Comment by dleangen** [comment]
Ok, thanks. If there are docs for this, please point me there and ignore my questions. 😀

Does the layout have to be the same for all projects in a workspace?

If I want to keep my current layout, what would I need to do?

**Comment by pkriens** [comment]
If you want to keep your current layout, just change the properties in maven-layout.bnd or remove the file. However, I would consider moving over unless you got thousands of projects.

**Comment by dleangen** [comment]
Does the layout have to be the same for all projects in a workspace?

**Comment by pkriens** [comment]
No, but it is HIGHLY recommended and new projects are always going to be generated using the info in `cnf`.

I don't know how many projects you have but I would bite the bullet. It has become a useful industry de-facto standard to layout the directories like maven.

**Comment by dleangen** [comment]
Ok, I'll just have to trust you on this one. I am in the process of completely rethinking everything from the ground up, since I have the opportunity to make a(nother) fresh start. I will do this in conjunction with my revision of your book (which I hope to get soon😀).

So I'll bit the bullet.

In the book, you may want to provide a bit more explanation to make it satisfactory for those who are even more skeptical than I am.
