### ISSUE TITLE
MQTT client can't reconnect

### ISSUE THREAD

**Issue by josejdunia** [aQute-os/biz.aQute.osgi.util#22]
There is a known issue with the Eclipse Paho library when the client loses connection with the broker (in the event of an internet outage for example) and it's not able to reconnect. The issue is described here: https://github.com/eclipse/paho.mqtt.java/issues/576

This is how it can be replicated:

```
- connect to a valid and reachable broker with connect option setAutomaticReconnect(true) and subscribe to a valid topic
- publish something on the topic -> data arrives
- cause a disruption on the network connection, e.g. disabling wifi on my laptop
- wait until the keep alive period has passed -> the internal.ClientState.checkForActivity message appears
- re-enable the network connection
- publish something on the topic -> no data arrives at the paho client
```

**Comment by pkriens** [comment]
There is a max reconnect delay set to 2 mins. Did you wait 2 mins?

**Comment by pkriens** [comment]
Closing this issue until a FINE log is given of a failing connection.
