### ISSUE TITLE
Is the namespace "osgi.enroute.authorization" still wanted?

### ISSUE THREAD

**Issue by stbischof** [aQute-os/biz.aQute.osgi.util#3]
https://github.com/aQute-os/biz.aQute.osgi.util/blob/e2ef91a4c3d48236551259c996533e3fefd11e38/biz.aQute.api/src/main/java/biz/aQute/authorization/api/AuthorizationConstants.java#L10

**Comment by pkriens** [comment]
thx, and now a PR? :-)
