### ISSUE TITLE
Default value of Permission-Glob

### ISSUE THREAD

**Issue by stbischof** [aQute-os/biz.aQute.osgi.util#8]
Should we change the default value from `gogo.command:none`  to `gogo.command:!*`

https://github.com/aQute-os/biz.aQute.osgi.util/blob/b85972fda46999a7224580b6a50862ff79bbbe0b/biz.aQute.shell.sshd.provider/src/main/java/biz/aQute/shell/sshd/config/SshdConfig.java#L36

**Comment by pkriens** [comment]
Globs do not have the !, the ! is part of Instructions. I think it would be confusing. To list commands, you need to do `(a|b|c)`. So in principle for this configuration you need a string that could never be a command.

**Comment by stbischof** [comment]
I just came up with this because `none` could be a command.

**Comment by pkriens** [comment]
I guess I'll take my changes with a developer that creates a 'none' command :-)
